/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputType } from "./components/my-input/my-input.types";
export { InputType } from "./components/my-input/my-input.types";
export namespace Components {
    interface MyInput {
        "disabled": boolean;
        "inputType": InputType;
        "label": string;
        "placeholder": string;
        "readonly": boolean;
    }
    interface MyTextarea {
        "cols": number;
        "disabled": boolean;
        "label": string;
        "placeholder": string;
        "rows": number;
    }
}
declare global {
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLMyTextareaElement extends Components.MyTextarea, HTMLStencilElement {
    }
    var HTMLMyTextareaElement: {
        prototype: HTMLMyTextareaElement;
        new (): HTMLMyTextareaElement;
    };
    interface HTMLElementTagNameMap {
        "my-input": HTMLMyInputElement;
        "my-textarea": HTMLMyTextareaElement;
    }
}
declare namespace LocalJSX {
    interface MyInput {
        "disabled"?: boolean;
        "inputType"?: InputType;
        "label"?: string;
        "placeholder"?: string;
        "readonly"?: boolean;
    }
    interface MyTextarea {
        "cols"?: number;
        "disabled"?: boolean;
        "label"?: string;
        "placeholder"?: string;
        "rows"?: number;
    }
    interface IntrinsicElements {
        "my-input": MyInput;
        "my-textarea": MyTextarea;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            "my-textarea": LocalJSX.MyTextarea & JSXBase.HTMLAttributes<HTMLMyTextareaElement>;
        }
    }
}
