/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputType } from "./components/my-input/my-input.types";
export { InputType } from "./components/my-input/my-input.types";
export namespace Components {
    interface MyInput {
        "disabled": boolean;
        "inputType": InputType;
        "label": string;
        "placeholder": string;
        "readonly": boolean;
    }
    interface MyTextarea {
        "cols": number;
        "disabled": boolean;
        "label": string;
        "placeholder": string;
        "rows": number;
    }
    interface WcSelect {
        "initialValue": string;
        "label": string;
        "options": Array<string>;
    }
    interface WcSelectView {
    }
}
declare global {
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLMyTextareaElement extends Components.MyTextarea, HTMLStencilElement {
    }
    var HTMLMyTextareaElement: {
        prototype: HTMLMyTextareaElement;
        new (): HTMLMyTextareaElement;
    };
    interface HTMLWcSelectElement extends Components.WcSelect, HTMLStencilElement {
    }
    var HTMLWcSelectElement: {
        prototype: HTMLWcSelectElement;
        new (): HTMLWcSelectElement;
    };
    interface HTMLWcSelectViewElement extends Components.WcSelectView, HTMLStencilElement {
    }
    var HTMLWcSelectViewElement: {
        prototype: HTMLWcSelectViewElement;
        new (): HTMLWcSelectViewElement;
    };
    interface HTMLElementTagNameMap {
        "my-input": HTMLMyInputElement;
        "my-textarea": HTMLMyTextareaElement;
        "wc-select": HTMLWcSelectElement;
        "wc-select-view": HTMLWcSelectViewElement;
    }
}
declare namespace LocalJSX {
    interface MyInput {
        "disabled"?: boolean;
        "inputType"?: InputType;
        "label"?: string;
        "placeholder"?: string;
        "readonly"?: boolean;
    }
    interface MyTextarea {
        "cols"?: number;
        "disabled"?: boolean;
        "label"?: string;
        "placeholder"?: string;
        "rows"?: number;
    }
    interface WcSelect {
        "initialValue"?: string;
        "label"?: string;
        "options"?: Array<string>;
    }
    interface WcSelectView {
    }
    interface IntrinsicElements {
        "my-input": MyInput;
        "my-textarea": MyTextarea;
        "wc-select": WcSelect;
        "wc-select-view": WcSelectView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            "my-textarea": LocalJSX.MyTextarea & JSXBase.HTMLAttributes<HTMLMyTextareaElement>;
            "wc-select": LocalJSX.WcSelect & JSXBase.HTMLAttributes<HTMLWcSelectElement>;
            "wc-select-view": LocalJSX.WcSelectView & JSXBase.HTMLAttributes<HTMLWcSelectViewElement>;
        }
    }
}
